# Generated by Django 5.2 on 2025-04-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendimento', models.CharField(max_length=20)),
                ('mix_produtos', models.CharField(max_length=30)),
                ('atendimento_agil', models.CharField(max_length=30)),
                ('valores_produtos', models.CharField(max_length=30)),
                ('prazo_entrega', models.CharField(max_length=30)),
                ('sugestao_melhoria', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
