# Generated by Django 5.2 on 2025-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
